Windows 2022 [semver:major]
CircleCI-Public/windows-orb pull request #30
Opened 2022-03-21 19:14 UTC by mrothstein74

@felicianotech  @KyleTryon Made requested changes.

2022-03-21 19:46 UTC, EricRibeiro commented
The integration test is failing. 

Also, it might be a good idea to include a test for each image/variant using matrix parameters.

2022-03-21 20:02 UTC, mrothstein74 commented
> 

@EricRibeiro should be fixed

2022-03-21 20:08 UTC, EricRibeiro commented
Awesome! 

Can you remove the [orb.yml](https://github.com/CircleCI-Public/windows-orb/pull/30/files#diff-10f861fbbd55bb7baa29cb4a3b36607a9eda4cf618daa1dd8499d9277a18a54f)? This file shouldn't be pushed to the repo.

Also, add integration tests for the other executors/variants?

2022-03-22 13:55 UTC, felicianotech commented
Let's not merge this even if it passes. I want to talk more broadly with the team on this approach to see if we all agree.

2022-03-23 15:38 UTC, felicianotech requested changes

2022-03-23 20:13 UTC, KyleTryon commented on .circleci/config.yml
> +     # - test-server-2019-cuda:
Why is this commented out?

2022-03-23 20:26 UTC, mrothstein74 commented on .circleci/config.yml
> +     # - test-server-2019-cuda:
> Why is this commented out?

commented out because image name wont exist until vm-service gets updated tomorrow

2022-03-23 23:30 UTC, mrothstein74 commented on .circleci/config.yml
> +     # - test-server-2019-cuda:
@KyleTryon vm-service has now been updated so i was able to put the test back in there.

2022-03-25 12:39 UTC, merged