[semver:patch] migrate to orb tools 11
CircleCI-Public/windows-orb pull request #32
Opened 2022-03-30 05:58 UTC by HennaAbbas

migration from  to orb tools 11

2022-03-30 15:30 UTC, KyleTryon requested changes
I modified the title of the PR, the `[semver:segment]` syntax was proprietary to CircleCI/Orbs and no longer needed. We now use https://www.conventionalcommits.org/en/v1.0.0/

2022-03-30 15:30 UTC, KyleTryon commented on .circleci/test-deploy.yml
> +  test-server-2019:
Ensure each job that has been imported by the migrate script here is tested in the workflow below. I'll tag it below.

2022-03-30 15:30 UTC, KyleTryon commented on .circleci/test-deploy.yml
> +            - command-tests
Remove this as well.

2022-03-30 15:30 UTC, KyleTryon commented on .circleci/test-deploy.yml
> +          requires:
Ensure every job that was imported above is tested here. Take a look at the original workflow (from the current source, before the migrate script was ran) to see how those jobs were ran previously. This publish job should not run until each of the test jobs above has ran first.

2022-04-05 18:23 UTC, felicianotech commented
@HennaAbbas Still working on this?

2022-04-08 15:31 UTC, HennaAbbas commented on .circleci/test-deploy.yml
> +      - command-tests:
removed line 49

2022-04-08 15:32 UTC, HennaAbbas commented on .circleci/test-deploy.yml
> +  test-server-2019:
ran test-server-2019,  test-server-2019-cude,  test-server-2022

2022-04-22 20:26 UTC, closed without merging